/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 19/07/2022 14:50:00
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     200000000
#define MX_HCLKFreq_Value                       200000000
#define MX_FCLKCortexFreq_Value                 200000000
#define MX_CortexFreq_Value                     200000000
#define MX_AHBFreq_Value                        200000000
#define MX_APB1Freq_Value                       50000000
#define MX_APB2Freq_Value                       100000000
#define MX_APB1TimFreq_Value                    100000000
#define MX_APB2TimFreq_Value                    200000000
#define MX_EthernetFreq_Value                   200000000
#define MX_CECFreq_Value                        32786
#define MX_LCDTFToutputFreq_Value               24000000
#define MX_I2C1Freq_Value                       50000000
#define MX_I2C2Freq_Value                       50000000
#define MX_I2C3Freq_Value                       50000000
#define MX_I2C4Freq_Value                       50000000
#define MX_I2SFreq_Value                        96000000
#define MX_SAI1Freq_Value                       96000000
#define MX_SAI2Freq_Value                       96000000
#define MX_SDMMCFreq_Value                      200000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     100000000
#define MX_USART2Freq_Value                     50000000
#define MX_USART3Freq_Value                     50000000
#define MX_UART4Freq_Value                      50000000
#define MX_UART5Freq_Value                      50000000
#define MX_UART8Freq_Value                      50000000
#define MX_UART7Freq_Value                      50000000
#define MX_USART6Freq_Value                     100000000
#define MX_USBFreq_Value                        200000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     50000000
#define MX_SPDIFRXFreq_Value                    96000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    200000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DMA2D      --------------------------------*/

#define MX_DMA2D                                1

/* GPIO Configuration */

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TX_EN_Pin                        PG11
#define MX_ETH_TX_EN_GPIOx                      GPIOG
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD1_Pin                         PG14
#define MX_ETH_TXD1_GPIOx                       GPIOG
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_14
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD0_Pin                         PG13
#define MX_ETH_TXD0_GPIOx                       GPIOG
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC ETH_IRQn */
#define MX_ETH_IRQn_interruptPremptionPriority  0
#define MX_ETH_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ETH_IRQn_Subriority                  0

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_FMC_D8_DA8_Pin                       PE11
#define MX_FMC_D8_DA8_GPIOx                     GPIOE
#define MX_FMC_D8_DA8_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D8_DA8_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D8_DA8_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_D8_DA8_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D8_DA8_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF0 */
#define MX_FMC_A0_Pin                           PF0
#define MX_FMC_A0_GPIOx                         GPIOF
#define MX_FMC_A0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A0_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_A0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A0_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF1 */
#define MX_FMC_A1_Pin                           PF1
#define MX_FMC_A1_GPIOx                         GPIOF
#define MX_FMC_A1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A1_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_A1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_DA3_Pin                       PD1
#define MX_FMC_D3_DA3_GPIOx                     GPIOD
#define MX_FMC_D3_DA3_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D3_DA3_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_DA3_GPIO_Pin                  GPIO_PIN_1
#define MX_FMC_D3_DA3_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D3_DA3_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF2 */
#define MX_FMC_A2_Pin                           PF2
#define MX_FMC_A2_GPIOx                         GPIOF
#define MX_FMC_A2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A2_GPIO_Pin                      GPIO_PIN_2
#define MX_FMC_A2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF11 */
#define MX_FMC_SDNRAS_Pin                       PF11
#define MX_FMC_SDNRAS_GPIOx                     GPIOF
#define MX_FMC_SDNRAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNRAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNRAS_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_SDNRAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNRAS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF3 */
#define MX_FMC_A3_Pin                           PF3
#define MX_FMC_A3_GPIOx                         GPIOF
#define MX_FMC_A3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A3_GPIO_Pin                      GPIO_PIN_3
#define MX_FMC_A3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PH3 */
#define MX_FMC_SDNE0_Pin                        PH3
#define MX_FMC_SDNE0_GPIOx                      GPIOH
#define MX_FMC_SDNE0_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNE0_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNE0_GPIO_Pin                   GPIO_PIN_3
#define MX_FMC_SDNE0_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNE0_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF4 */
#define MX_FMC_A4_Pin                           PF4
#define MX_FMC_A4_GPIOx                         GPIOF
#define MX_FMC_A4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A4_GPIO_Pin                      GPIO_PIN_4
#define MX_FMC_A4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF5 */
#define MX_FMC_A5_Pin                           PF5
#define MX_FMC_A5_GPIOx                         GPIOF
#define MX_FMC_A5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A5_GPIO_Pin                      GPIO_PIN_5
#define MX_FMC_A5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PH5 */
#define MX_FMC_SDNWE_Pin                        PH5
#define MX_FMC_SDNWE_GPIOx                      GPIOH
#define MX_FMC_SDNWE_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNWE_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNWE_GPIO_Pin                   GPIO_PIN_5
#define MX_FMC_SDNWE_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNWE_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF12 */
#define MX_FMC_A6_Pin                           PF12
#define MX_FMC_A6_GPIOx                         GPIOF
#define MX_FMC_A6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A6_GPIO_Pin                      GPIO_PIN_12
#define MX_FMC_A6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG0 */
#define MX_FMC_A10_Pin                          PG0
#define MX_FMC_A10_GPIOx                        GPIOG
#define MX_FMC_A10_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A10_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A10_GPIO_Pin                     GPIO_PIN_0
#define MX_FMC_A10_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A10_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD9 */
#define MX_FMC_D14_DA14_Pin                     PD9
#define MX_FMC_D14_DA14_GPIOx                   GPIOD
#define MX_FMC_D14_DA14_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D14_DA14_GPIO_Pin                GPIO_PIN_9
#define MX_FMC_D14_DA14_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D14_DA14_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PF13 */
#define MX_FMC_A7_Pin                           PF13
#define MX_FMC_A7_GPIOx                         GPIOF
#define MX_FMC_A7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A7_GPIO_Pin                      GPIO_PIN_13
#define MX_FMC_A7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF14 */
#define MX_FMC_A8_Pin                           PF14
#define MX_FMC_A8_GPIOx                         GPIOF
#define MX_FMC_A8_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A8_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A8_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_A8_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A8_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG1 */
#define MX_FMC_A11_Pin                          PG1
#define MX_FMC_A11_GPIOx                        GPIOG
#define MX_FMC_A11_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A11_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A11_GPIO_Pin                     GPIO_PIN_1
#define MX_FMC_A11_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A11_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF15 */
#define MX_FMC_A9_Pin                           PF15
#define MX_FMC_A9_GPIOx                         GPIOF
#define MX_FMC_A9_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A9_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A9_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_A9_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A9_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PC3 */
#define MX_FMC_SDCKE0_Pin                       PC3
#define MX_FMC_SDCKE0_GPIOx                     GPIOC
#define MX_FMC_SDCKE0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDCKE0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDCKE0_GPIO_Pin                  GPIO_PIN_3
#define MX_FMC_SDCKE0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDCKE0_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_FMC_D11_DA11_Pin                     PE14
#define MX_FMC_D11_DA11_GPIOx                   GPIOE
#define MX_FMC_D11_DA11_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D11_DA11_GPIO_Pin                GPIO_PIN_14
#define MX_FMC_D11_DA11_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D11_DA11_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FMC_A16_CLE_Pin                      PD11
#define MX_FMC_A16_CLE_GPIOx                    GPIOD
#define MX_FMC_A16_CLE_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A16_CLE_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A16_CLE_GPIO_Pin                 GPIO_PIN_11
#define MX_FMC_A16_CLE_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A16_CLE_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_DA4_Pin                       PE7
#define MX_FMC_D4_DA4_GPIOx                     GPIOE
#define MX_FMC_D4_DA4_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D4_DA4_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_DA4_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_D4_DA4_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D4_DA4_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_DA7_Pin                       PE10
#define MX_FMC_D7_DA7_GPIOx                     GPIOE
#define MX_FMC_D7_DA7_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D7_DA7_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_DA7_GPIO_Pin                  GPIO_PIN_10
#define MX_FMC_D7_DA7_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D7_DA7_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG5 */
#define MX_FMC_A15_BA1_Pin                      PG5
#define MX_FMC_A15_BA1_GPIOx                    GPIOG
#define MX_FMC_A15_BA1_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A15_BA1_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A15_BA1_GPIO_Pin                 GPIO_PIN_5
#define MX_FMC_A15_BA1_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A15_BA1_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE1 */
#define MX_FMC_NBL1_Pin                         PE1
#define MX_FMC_NBL1_GPIOx                       GPIOE
#define MX_FMC_NBL1_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL1_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL1_GPIO_Pin                    GPIO_PIN_1
#define MX_FMC_NBL1_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE0 */
#define MX_FMC_NBL0_Pin                         PE0
#define MX_FMC_NBL0_GPIOx                       GPIOE
#define MX_FMC_NBL0_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL0_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL0_GPIO_Pin                    GPIO_PIN_0
#define MX_FMC_NBL0_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_DA0_Pin                       PD14
#define MX_FMC_D0_DA0_GPIOx                     GPIOD
#define MX_FMC_D0_DA0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D0_DA0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_DA0_GPIO_Pin                  GPIO_PIN_14
#define MX_FMC_D0_DA0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D0_DA0_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_DA5_Pin                       PE8
#define MX_FMC_D5_DA5_GPIOx                     GPIOE
#define MX_FMC_D5_DA5_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D5_DA5_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_DA5_GPIO_Pin                  GPIO_PIN_8
#define MX_FMC_D5_DA5_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D5_DA5_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE13 */
#define MX_FMC_D10_DA10_Pin                     PE13
#define MX_FMC_D10_DA10_GPIOx                   GPIOE
#define MX_FMC_D10_DA10_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D10_DA10_GPIO_Pin                GPIO_PIN_13
#define MX_FMC_D10_DA10_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D10_DA10_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_FMC_D13_DA13_Pin                     PD8
#define MX_FMC_D13_DA13_GPIOx                   GPIOD
#define MX_FMC_D13_DA13_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D13_DA13_GPIO_Pin                GPIO_PIN_8
#define MX_FMC_D13_DA13_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D13_DA13_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PG4 */
#define MX_FMC_A14_BA0_Pin                      PG4
#define MX_FMC_A14_BA0_GPIOx                    GPIOG
#define MX_FMC_A14_BA0_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A14_BA0_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A14_BA0_GPIO_Pin                 GPIO_PIN_4
#define MX_FMC_A14_BA0_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A14_BA0_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG8 */
#define MX_FMC_SDCLK_Pin                        PG8
#define MX_FMC_SDCLK_GPIOx                      GPIOG
#define MX_FMC_SDCLK_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDCLK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDCLK_GPIO_Pin                   GPIO_PIN_8
#define MX_FMC_SDCLK_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDCLK_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_FMC_D12_DA12_Pin                     PE15
#define MX_FMC_D12_DA12_GPIOx                   GPIOE
#define MX_FMC_D12_DA12_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D12_DA12_GPIO_Pin                GPIO_PIN_15
#define MX_FMC_D12_DA12_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D12_DA12_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD15 */
#define MX_FMC_D1_DA1_Pin                       PD15
#define MX_FMC_D1_DA1_GPIOx                     GPIOD
#define MX_FMC_D1_DA1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D1_DA1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_DA1_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_D1_DA1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D1_DA1_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG15 */
#define MX_FMC_SDNCAS_Pin                       PG15
#define MX_FMC_SDNCAS_GPIOx                     GPIOG
#define MX_FMC_SDNCAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNCAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNCAS_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_SDNCAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNCAS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_FMC_D9_DA9_Pin                       PE12
#define MX_FMC_D9_DA9_GPIOx                     GPIOE
#define MX_FMC_D9_DA9_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D9_DA9_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D9_DA9_GPIO_Pin                  GPIO_PIN_12
#define MX_FMC_D9_DA9_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D9_DA9_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_DA2_Pin                       PD0
#define MX_FMC_D2_DA2_GPIOx                     GPIOD
#define MX_FMC_D2_DA2_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D2_DA2_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_DA2_GPIO_Pin                  GPIO_PIN_0
#define MX_FMC_D2_DA2_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D2_DA2_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_DA6_Pin                       PE9
#define MX_FMC_D6_DA6_GPIOx                     GPIOE
#define MX_FMC_D6_DA6_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D6_DA6_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_DA6_GPIO_Pin                  GPIO_PIN_9
#define MX_FMC_D6_DA6_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D6_DA6_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD10 */
#define MX_FMC_D15_DA15_Pin                     PD10
#define MX_FMC_D15_DA15_GPIOx                   GPIOD
#define MX_FMC_D15_DA15_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D15_DA15_GPIO_Pin                GPIO_PIN_10
#define MX_FMC_D15_DA15_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D15_DA15_GPIO_Mode               GPIO_MODE_AF_PP

/*-------------------------------- LTDC       --------------------------------*/

#define MX_LTDC                                 1

/* GPIO Configuration */

/* Pin PI14 */
#define MX_LTDC_CLK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_LTDC_CLK_Pin                         PI14
#define MX_LTDC_CLK_GPIOx                       GPIOI
#define MX_LTDC_CLK_GPIO_PuPd                   GPIO_NOPULL
#define MX_LTDC_CLK_GPIO_Pin                    GPIO_PIN_14
#define MX_LTDC_CLK_GPIO_AF                     GPIO_AF14_LTDC
#define MX_LTDC_CLK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB8 */
#define MX_LTDC_B6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B6_Pin                          PB8
#define MX_LTDC_B6_GPIOx                        GPIOB
#define MX_LTDC_B6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_B6_GPIO_Pin                     GPIO_PIN_8
#define MX_LTDC_B6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB9 */
#define MX_LTDC_B7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B7_Pin                          PB9
#define MX_LTDC_B7_GPIOx                        GPIOB
#define MX_LTDC_B7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_B7_GPIO_Pin                     GPIO_PIN_9
#define MX_LTDC_B7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI4 */
#define MX_LTDC_B4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B4_Pin                          PI4
#define MX_LTDC_B4_GPIOx                        GPIOI
#define MX_LTDC_B4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_B4_GPIO_Pin                     GPIO_PIN_4
#define MX_LTDC_B4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI5 */
#define MX_LTDC_B5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B5_Pin                          PI5
#define MX_LTDC_B5_GPIOx                        GPIOI
#define MX_LTDC_B5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_B5_GPIO_Pin                     GPIO_PIN_5
#define MX_LTDC_B5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD3 */
#define MX_LTDC_G7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G7_Pin                          PD3
#define MX_LTDC_G7_GPIOx                        GPIOD
#define MX_LTDC_G7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G7_GPIO_Pin                     GPIO_PIN_3
#define MX_LTDC_G7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI10 */
#define MX_LTDC_HSYNC_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LTDC_HSYNC_Pin                       PI10
#define MX_LTDC_HSYNC_GPIOx                     GPIOI
#define MX_LTDC_HSYNC_GPIO_PuPd                 GPIO_NOPULL
#define MX_LTDC_HSYNC_GPIO_Pin                  GPIO_PIN_10
#define MX_LTDC_HSYNC_GPIO_AF                   GPIO_AF14_LTDC
#define MX_LTDC_HSYNC_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PJ15 */
#define MX_LTDC_B3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B3_Pin                          PJ15
#define MX_LTDC_B3_GPIOx                        GPIOJ
#define MX_LTDC_B3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_B3_GPIO_Pin                     GPIO_PIN_15
#define MX_LTDC_B3_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI0 */
#define MX_LTDC_G5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G5_Pin                          PI0
#define MX_LTDC_G5_GPIOx                        GPIOI
#define MX_LTDC_G5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G5_GPIO_Pin                     GPIO_PIN_0
#define MX_LTDC_G5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI1 */
#define MX_LTDC_G6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G6_Pin                          PI1
#define MX_LTDC_G6_GPIOx                        GPIOI
#define MX_LTDC_G6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G6_GPIO_Pin                     GPIO_PIN_1
#define MX_LTDC_G6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG10 */
#define MX_LTDC_G3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G3_Pin                          PG10
#define MX_LTDC_G3_GPIOx                        GPIOG
#define MX_LTDC_G3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G3_GPIO_Pin                     GPIO_PIN_10
#define MX_LTDC_G3_GPIO_AF                      GPIO_AF9_LTDC
#define MX_LTDC_G3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PH15 */
#define MX_LTDC_G4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G4_Pin                          PH15
#define MX_LTDC_G4_GPIOx                        GPIOH
#define MX_LTDC_G4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G4_GPIO_Pin                     GPIO_PIN_15
#define MX_LTDC_G4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI9 */
#define MX_LTDC_VSYNC_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LTDC_VSYNC_Pin                       PI9
#define MX_LTDC_VSYNC_GPIOx                     GPIOI
#define MX_LTDC_VSYNC_GPIO_PuPd                 GPIO_NOPULL
#define MX_LTDC_VSYNC_GPIO_Pin                  GPIO_PIN_9
#define MX_LTDC_VSYNC_GPIO_AF                   GPIO_AF14_LTDC
#define MX_LTDC_VSYNC_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PH13 */
#define MX_LTDC_G2_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G2_Pin                          PH13
#define MX_LTDC_G2_GPIOx                        GPIOH
#define MX_LTDC_G2_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_G2_GPIO_Pin                     GPIO_PIN_13
#define MX_LTDC_G2_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA8 */
#define MX_LTDC_R6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R6_Pin                          PA8
#define MX_LTDC_R6_GPIOx                        GPIOA
#define MX_LTDC_R6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_R6_GPIO_Pin                     GPIO_PIN_8
#define MX_LTDC_R6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG6 */
#define MX_LTDC_R7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R7_Pin                          PG6
#define MX_LTDC_R7_GPIOx                        GPIOG
#define MX_LTDC_R7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_R7_GPIO_Pin                     GPIO_PIN_6
#define MX_LTDC_R7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA11 */
#define MX_LTDC_R4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R4_Pin                          PA11
#define MX_LTDC_R4_GPIOx                        GPIOA
#define MX_LTDC_R4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_R4_GPIO_Pin                     GPIO_PIN_11
#define MX_LTDC_R4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_LTDC_R5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R5_Pin                          PA12
#define MX_LTDC_R5_GPIOx                        GPIOA
#define MX_LTDC_R5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_R5_GPIO_Pin                     GPIO_PIN_12
#define MX_LTDC_R5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK7 */
#define MX_LTDC_DE_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_DE_Pin                          PK7
#define MX_LTDC_DE_GPIOx                        GPIOK
#define MX_LTDC_DE_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_DE_GPIO_Pin                     GPIO_PIN_7
#define MX_LTDC_DE_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_DE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PH9 */
#define MX_LTDC_R3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R3_Pin                          PH9
#define MX_LTDC_R3_GPIOx                        GPIOH
#define MX_LTDC_R3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LTDC_R3_GPIO_Pin                     GPIO_PIN_9
#define MX_LTDC_R3_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R3_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PB7 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Pin                        PB7
#define MX_USART1_RX_GPIOx                      GPIOB
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

